#!/bin/bash

base=/var/spool/simta
critical=1000
warn=500
age=5

while getopts a:c:q:w: opt; do
    case $opt in
    a)  age=$OPTARG
        ;;
    c)  critical=$OPTARG
        ;;
    w)  warn=$OPTARG
        ;;
    q)  queue=${base}/$OPTARG
        simqcflag="-${OPTARG::1}"
        ;;
    esac
done

if [[ ! -d $queue ]]; then
    echo "No queue directory: $queue"
    exit 3
fi

qcount=$(find $queue -ignore_readdir_race -type f -name 'D*' -mmin +$age 2>/dev/null | sed -e 's/D/E/;' | xargs grep -l '^J2$' | wc -l)
echo "$qcount jailed messages in $queue"
if [[ $qcount -gt 0 ]]; then
    echo
    simqc $simqcflag -S -a
fi
if [[ $qcount -gt $critical ]]; then
    exit 2
elif [[ $qcount -gt $warn ]]; then
    exit 1
fi

exit 0
