#!/bin/bash

# simqclean
#
#	Given a uniqname, remove all pending messages sent by that
#	uniqname from the simta queues on the localhost.  Removed
#	messages are archived under /var/tmp for later analysis.


timestamp=$(date +%F-%T)
pre=/var/tmp/simqclean
simtadir=/var/spool/simta

usage() {
    echo "Usage: $0 <uniqname> [ <uniqname> ... ]"
    echo "       $0 -s <string> "
    exit 1
}

if [[ $# -eq 0 ]] || [[ $1 = -h ]]; then
    usage
fi

if [[ $1 = -s ]]; then
    unsafe='true'
    shift
fi

rndc flush

state=started
for p in "$@" ; do
    if [[ $unsafe ]]; then
        echo "Removing messages containing $p"
        pattern=$p
    else
        echo "Removing messages from $p"
        pattern="^((X-Originating-User:)|([[:space:]]Authuser)) $p;?$"
    fi

    savedir=${pre}/${p}/${timestamp}

    if ! [[ -d $savedir ]]; then
        mkdir -p "${savedir}" || exit 1
    fi

    for q in slow fast; do
        find $simtadir/$q -ignore_readdir_race -maxdepth 1 -name D\* -type f | xargs -r cat 2>/dev/null | grep -q "$pattern"
        if [[ $? -eq 0 ]]; then
            if [[ $q = 'fast' ]]; then
                echo 'Stopping simta...'
                if which systemctl &>/dev/null ; then
                    systemctl stop simta
                else
                    /etc/init.d/simta stop
                fi
                state=stopped
            fi
            echo "Cleaning $q"
            find $simtadir/$q -ignore_readdir_race -maxdepth 1 -name D\* -type f | xargs -r egrep -l "$pattern" | sed -e 'p; s/D/E/;' | \
                    xargs -r -I spam mv spam "$savedir"
        else
            echo "No cleaning needed in $q"
        fi
    done
done

if [[ $state = 'stopped' ]]; then
	sleep 4
	echo 'Starting simta...'
        if which systemctl &>/dev/null ; then
            systemctl start simta
        else
            /etc/init.d/simta start
        fi
fi

