#!/bin/bash

export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/rsug/bin

name=simtamaint
confdir=/etc/sysconfig/nag

if [ -d /var/spool/simta/etc ]; then
    day=`date -d yesterday +%a`
    cd /var/spool/simta/etc
    rm -rf $day &>/dev/null
    mkdir $day
    find . -maxdepth 1 -type f -exec mv {} $day \;
fi
