#!/bin/bash -e

## simtrans
##
## 	Given a regular expression, extract all simta logfile
##	entries	for the transaction(s) associated with that
##	expression.
##
##	This is useful when you have an anomalous env {D,E}
##	<MID> file pair from the simta spool and you want
##	a bigger picture of what the sender was doing.

logfile=${logfile:-/var/log/mail}

## In case we're handed an IP address as our search pattern, we
## need to exclude the parent process' logging the child creation,
## as we don't want the transaction ID of the parent.  E.g.,
## '7642.1293473885' is the parent tid and '605.1302669858' is the
## child tid here:
#
# simta[7642.1293473885]: Child Start 605.1302669858:
# simta[7642.1293473885]: Child Exited 605.1302669858:
#
## Note that there are two lines containing 'Connect.stat' for
## each session, one from the child and one from the parent,
## we must weed out those as well.
#
# simta[7642.1293473885]: Connect.stat

tmpfile=$(mktemp /tmp/.simtrans.XXXXXXXX)
grep="fgrep"
cat="cat"

if { echo $logfile | grep -q "gz$"; }; then
    grep="zfgrep"
    cat="zcat"
fi

for pattern in "$@" ; do
    $cat $logfile | awk -v p="$pattern" '
	( $0 ~ p ) && ( $5 ~ /^simta\[.*\]:$/ ) &&
	( $6 " " $7 !~ /Child (Start|Exited)/ ) &&
	( $6  !~ /Connect\.stat/ ) {
	    t=$5;
	    gsub(/simta\[|\]:/, "", t);
	    tid[t]++;
	}
	END {
	    for ( t in tid ) print t;
	}'
done >| $tmpfile

$grep -f $tmpfile $logfile
rm -f $tmpfile

## Instead of a straight fgrep, we might want consider
## grepping for  "simta\[${tid}\]:" plus " ${tid}:? ".
## The fgrep has the possibility of false positives.
