#!/bin/bash

simtadir=/var/spool/simta

if [[ -d $simtadir/etc ]]; then
    # Clean up old files
    find $simtadir/etc -ignore_readdir_race -type f -mtime +7 -delete

    # Archive new files
    for statfile in $(find $simtadir/etc -ignore_readdir_race -maxdepth 1 -name \*.\* -type f) ; do
        day=$(date -r $statfile +%a)
        mkdir -p $simtadir/etc/$day
        mv $statfile $simtadir/etc/$day
    done
fi
